name: job bot v2

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Use the version you prefer

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython discord.py python-dotenv # Install the required packages

      # Step 4: Run the job monitor script
      - name: Run job monitor script
        run: python monitor.py  # Adjust to the name of your script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Environment variable for Discord webhook
